/* GENERATED by tools/fetch_catalog.py — do not edit by hand.
   Play counts and totals come from data/stats-manual.json. */
window.CATALOG = {
  "generated": true,
  "artist": "Jones RX",
  "tracks": [
    {
      "slug": "luv-u",
      "title": "Luv U",
      "album": "Luv U",
      "year": "2026",
      "released": "2026-04-10",
      "durationMs": 249391,
      "duration": "4:09",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/d2/9e/d6/d29ed66a-7dbc-c57f-6951-6b5b722b68c6/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 1,
      "appleUrl": "https://music.apple.com/us/album/luv-u/1887050586?i=1887050587&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "58",
      "playSources": {
        "soundcloud": 23,
        "youtube": 35
      },
      "local": "assets/catalog/luv-u.mp3"
    },
    {
      "slug": "crash-out",
      "title": "Crash Out",
      "album": "Crash Out",
      "year": "2025",
      "released": "2025-07-18",
      "durationMs": 159528,
      "duration": "2:39",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/f1/b4/45/f1b445db-b24d-6d7a-3cee-bb590a1c6480/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 1,
      "appleUrl": "https://music.apple.com/us/album/crash-out/1822544140?i=1822544141&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "597",
      "playSources": {
        "soundcloud": 243,
        "youtube": 354
      },
      "local": "assets/catalog/crash-out.mp3"
    },
    {
      "slug": "give-up-go-home",
      "title": "Give Up / Go Home",
      "album": "Give Up / Go Home",
      "year": "2025",
      "released": "2025-04-30",
      "durationMs": 186864,
      "duration": "3:06",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/ca/e1/9f/cae19f4e-8e9d-4270-0f86-95803b8fb7bf/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 1,
      "appleUrl": "https://music.apple.com/us/album/give-up-go-home/1801621920?i=1801621921&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "178",
      "playSources": {
        "soundcloud": 14,
        "youtube": 164
      },
      "local": "assets/catalog/give-up-go-home.mp3"
    },
    {
      "slug": "drop-dead",
      "title": "DROP DEAD",
      "album": "DROP DEAD",
      "year": "2024",
      "released": "2024-10-31",
      "durationMs": 144048,
      "duration": "2:24",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/65/81/ef/6581ef50-660f-48a4-52c2-5f580b18c0a9/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 1,
      "appleUrl": "https://music.apple.com/us/album/drop-dead/1776439287?i=1776439288&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "177",
      "playSources": {
        "soundcloud": 36,
        "youtube": 141
      },
      "local": "assets/catalog/drop-dead.mp3"
    },
    {
      "slug": "times-up-intro",
      "title": "Times Up (Intro)",
      "album": "Lost CTRL",
      "year": "2024",
      "released": "2024-05-31",
      "durationMs": 114648,
      "duration": "1:54",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/9a/41/da/9a41da6b-b9e6-0066-2a43-203756eb9b0c/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 1,
      "appleUrl": "https://music.apple.com/us/album/times-up-intro/1779309073?i=1779309074&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "115",
      "playSources": {
        "soundcloud": 39,
        "youtube": 76
      },
      "local": "assets/catalog/times-up-intro.mp3"
    },
    {
      "slug": "new-low-feat-steelpraud",
      "title": "New Low (feat. SteelPraud)",
      "album": "Lost CTRL",
      "year": "2024",
      "released": "2024-05-31",
      "durationMs": 178752,
      "duration": "2:58",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/9a/41/da/9a41da6b-b9e6-0066-2a43-203756eb9b0c/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 2,
      "appleUrl": "https://music.apple.com/us/album/new-low-feat-steelpraud/1779309073?i=1779309075&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "1567",
      "playSources": {
        "spotify": 1107,
        "soundcloud": 151,
        "youtube": 309
      },
      "local": "assets/catalog/new-low-feat-steelpraud.mp3"
    },
    {
      "slug": "two-face",
      "title": "Two Face",
      "album": "Lost CTRL",
      "year": "2024",
      "released": "2024-05-31",
      "durationMs": 135984,
      "duration": "2:15",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/9a/41/da/9a41da6b-b9e6-0066-2a43-203756eb9b0c/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 3,
      "appleUrl": "https://music.apple.com/us/album/two-face/1779309073?i=1779309078&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "250",
      "playSources": {
        "soundcloud": 17,
        "youtube": 233
      },
      "local": "assets/catalog/two-face.mp3"
    },
    {
      "slug": "upside-down",
      "title": "Upside Down",
      "album": "Lost CTRL",
      "year": "2024",
      "released": "2024-05-31",
      "durationMs": 124320,
      "duration": "2:04",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/9a/41/da/9a41da6b-b9e6-0066-2a43-203756eb9b0c/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 4,
      "appleUrl": "https://music.apple.com/us/album/upside-down/1779309073?i=1779309499&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "1688",
      "playSources": {
        "spotify": 1191,
        "soundcloud": 22,
        "youtube": 475
      },
      "local": "assets/catalog/upside-down.mp3"
    },
    {
      "slug": "painful",
      "title": "Painful",
      "album": "Lost CTRL",
      "year": "2024",
      "released": "2024-05-31",
      "durationMs": 200072,
      "duration": "3:20",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/9a/41/da/9a41da6b-b9e6-0066-2a43-203756eb9b0c/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 5,
      "appleUrl": "https://music.apple.com/us/album/painful/1779309073?i=1779309501&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "5473",
      "playSources": {
        "spotify": 4766,
        "soundcloud": 59,
        "youtube": 648
      },
      "local": "assets/catalog/painful.mp3"
    },
    {
      "slug": "atd",
      "title": "ATD",
      "album": "Lost CTRL",
      "year": "2024",
      "released": "2024-05-31",
      "durationMs": 163082,
      "duration": "2:43",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/9a/41/da/9a41da6b-b9e6-0066-2a43-203756eb9b0c/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 6,
      "appleUrl": "https://music.apple.com/us/album/atd/1779309073?i=1779309502&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "183",
      "playSources": {
        "soundcloud": 43,
        "youtube": 140
      },
      "local": "assets/catalog/atd.mp3"
    },
    {
      "slug": "close",
      "title": "Close",
      "album": "Lost CTRL",
      "year": "2024",
      "released": "2024-05-31",
      "durationMs": 165773,
      "duration": "2:45",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/9a/41/da/9a41da6b-b9e6-0066-2a43-203756eb9b0c/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 7,
      "appleUrl": "https://music.apple.com/us/album/close/1779309073?i=1779309503&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "483",
      "playSources": {
        "soundcloud": 21,
        "youtube": 462
      },
      "local": "assets/catalog/close.mp3"
    },
    {
      "slug": "new-low",
      "title": "New Low",
      "album": "New Low",
      "year": "2024",
      "released": "2024-03-15",
      "durationMs": 178752,
      "duration": "2:58",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/98/75/ea/9875ea39-3fbd-cbdd-9b2b-bd31c4dedadb/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 1,
      "appleUrl": "https://music.apple.com/us/album/new-low/1778561254?i=1778561255&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "1215",
      "playSources": {
        "spotify": 1107,
        "soundcloud": 3,
        "youtube": 105
      },
      "local": "assets/catalog/new-low.mp3"
    },
    {
      "slug": "awhf",
      "title": "AWHF",
      "album": "TOXIC",
      "year": "2023",
      "released": "2023-10-12",
      "durationMs": 183724,
      "duration": "3:03",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/e2/e4/52/e2e45265-01ad-26fb-b943-20341d5daf86/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 1,
      "appleUrl": "https://music.apple.com/us/album/awhf/1778545382?i=1778545383&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "64",
      "playSources": {
        "soundcloud": 6,
        "youtube": 58
      },
      "local": "assets/catalog/awhf.mp3"
    },
    {
      "slug": "bloodline",
      "title": "Bloodline",
      "album": "TOXIC",
      "year": "2023",
      "released": "2023-10-12",
      "durationMs": 190080,
      "duration": "3:10",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/e2/e4/52/e2e45265-01ad-26fb-b943-20341d5daf86/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 2,
      "appleUrl": "https://music.apple.com/us/album/bloodline/1778545382?i=1778545384&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "51",
      "playSources": {
        "soundcloud": 2,
        "youtube": 49
      },
      "local": "assets/catalog/bloodline.mp3"
    },
    {
      "slug": "toxic",
      "title": "Toxic",
      "album": "TOXIC",
      "year": "2023",
      "released": "2023-10-12",
      "durationMs": 201231,
      "duration": "3:21",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/e2/e4/52/e2e45265-01ad-26fb-b943-20341d5daf86/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 3,
      "appleUrl": "https://music.apple.com/us/album/toxic/1778545382?i=1778545385&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "7",
      "playSources": {
        "soundcloud": 7
      },
      "local": "assets/catalog/toxic.mp3"
    },
    {
      "slug": "patron",
      "title": "Patrón",
      "album": "Starstruck",
      "year": "2023",
      "released": "2023-04-15",
      "durationMs": 204904,
      "duration": "3:24",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/5e/ca/4b/5eca4ba3-9e67-4284-02f0-7bde6b456a54/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 1,
      "appleUrl": "https://music.apple.com/us/album/patr%C3%B3n/1778581995?i=1778581996&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "337",
      "playSources": {
        "soundcloud": 69,
        "youtube": 268
      },
      "local": "assets/catalog/patron.mp3"
    },
    {
      "slug": "slow-me-down",
      "title": "Slow Me Down",
      "album": "Starstruck",
      "year": "2023",
      "released": "2023-04-15",
      "durationMs": 186070,
      "duration": "3:06",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/5e/ca/4b/5eca4ba3-9e67-4284-02f0-7bde6b456a54/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 2,
      "appleUrl": "https://music.apple.com/us/album/slow-me-down/1778581995?i=1778581997&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "29",
      "playSources": {
        "soundcloud": 5,
        "youtube": 24
      },
      "local": "assets/catalog/slow-me-down.mp3"
    },
    {
      "slug": "vices",
      "title": "Vices",
      "album": "Starstruck",
      "year": "2023",
      "released": "2023-04-15",
      "durationMs": 155899,
      "duration": "2:35",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/5e/ca/4b/5eca4ba3-9e67-4284-02f0-7bde6b456a54/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 3,
      "appleUrl": "https://music.apple.com/us/album/vices/1778581995?i=1778581998&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "109",
      "playSources": {
        "soundcloud": 84,
        "youtube": 25
      },
      "local": "assets/catalog/vices.mp3"
    },
    {
      "slug": "fake-love",
      "title": "Fake Love",
      "album": "Starstruck",
      "year": "2023",
      "released": "2023-04-15",
      "durationMs": 128836,
      "duration": "2:08",
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/5e/ca/4b/5eca4ba3-9e67-4284-02f0-7bde6b456a54/artwork.jpg/600x600bb.jpg",
      "disc": 1,
      "trackNumber": 4,
      "appleUrl": "https://music.apple.com/us/album/fake-love/1778581995?i=1778582269&uo=4",
      "spotifyUrl": "",
      "popularity": null,
      "plays": "60",
      "playSources": {
        "soundcloud": 7,
        "youtube": 53
      },
      "local": "assets/catalog/fake-love.mp3"
    }
  ],
  "releases": [
    {
      "slug": "luv-u-single",
      "title": "Luv U",
      "kind": "Single",
      "year": "2026",
      "released": "2026-04-10",
      "trackCount": 1,
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/d2/9e/d6/d29ed66a-7dbc-c57f-6951-6b5b722b68c6/artwork.jpg/600x600bb.jpg",
      "appleUrl": "https://music.apple.com/us/album/luv-u-single/1887050586?uo=4",
      "spotifyUrl": "https://open.spotify.com/search/Luv%20U%20Jones%20RX"
    },
    {
      "slug": "crash-out-single",
      "title": "Crash Out",
      "kind": "Single",
      "year": "2025",
      "released": "2025-07-18",
      "trackCount": 1,
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/f1/b4/45/f1b445db-b24d-6d7a-3cee-bb590a1c6480/artwork.jpg/600x600bb.jpg",
      "appleUrl": "https://music.apple.com/us/album/crash-out-single/1822544140?uo=4",
      "spotifyUrl": "https://open.spotify.com/search/Crash%20Out%20Jones%20RX"
    },
    {
      "slug": "give-up-go-home-single",
      "title": "Give Up / Go Home",
      "kind": "Single",
      "year": "2025",
      "released": "2025-04-30",
      "trackCount": 1,
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/ca/e1/9f/cae19f4e-8e9d-4270-0f86-95803b8fb7bf/artwork.jpg/600x600bb.jpg",
      "appleUrl": "https://music.apple.com/us/album/give-up-go-home-single/1801621920?uo=4",
      "spotifyUrl": "https://open.spotify.com/search/Give%20Up%20/%20Go%20Home%20Jones%20RX"
    },
    {
      "slug": "drop-dead-single",
      "title": "DROP DEAD",
      "kind": "Single",
      "year": "2024",
      "released": "2024-10-31",
      "trackCount": 1,
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/65/81/ef/6581ef50-660f-48a4-52c2-5f580b18c0a9/artwork.jpg/600x600bb.jpg",
      "appleUrl": "https://music.apple.com/us/album/drop-dead-single/1776439287?uo=4",
      "spotifyUrl": "https://open.spotify.com/search/DROP%20DEAD%20Jones%20RX"
    },
    {
      "slug": "lost-ctrl",
      "title": "Lost CTRL",
      "kind": "Album",
      "year": "2024",
      "released": "2024-05-31",
      "trackCount": 7,
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/9a/41/da/9a41da6b-b9e6-0066-2a43-203756eb9b0c/artwork.jpg/600x600bb.jpg",
      "appleUrl": "https://music.apple.com/us/album/lost-ctrl/1779309073?uo=4",
      "spotifyUrl": "https://open.spotify.com/search/Lost%20CTRL%20Jones%20RX"
    },
    {
      "slug": "new-low-single",
      "title": "New Low",
      "kind": "Single",
      "year": "2024",
      "released": "2024-03-15",
      "trackCount": 1,
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/98/75/ea/9875ea39-3fbd-cbdd-9b2b-bd31c4dedadb/artwork.jpg/600x600bb.jpg",
      "appleUrl": "https://music.apple.com/us/album/new-low-single/1778561254?uo=4",
      "spotifyUrl": "https://open.spotify.com/search/New%20Low%20Jones%20RX"
    },
    {
      "slug": "toxic-single",
      "title": "TOXIC",
      "kind": "Single",
      "year": "2023",
      "released": "2023-10-12",
      "trackCount": 3,
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/e2/e4/52/e2e45265-01ad-26fb-b943-20341d5daf86/artwork.jpg/600x600bb.jpg",
      "appleUrl": "https://music.apple.com/us/album/toxic-single/1778545382?uo=4",
      "spotifyUrl": "https://open.spotify.com/search/TOXIC%20Jones%20RX"
    },
    {
      "slug": "starstruck-ep",
      "title": "Starstruck",
      "kind": "EP",
      "year": "2023",
      "released": "2023-04-15",
      "trackCount": 4,
      "art": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/5e/ca/4b/5eca4ba3-9e67-4284-02f0-7bde6b456a54/artwork.jpg/600x600bb.jpg",
      "appleUrl": "https://music.apple.com/us/album/starstruck-ep/1778581995?uo=4",
      "spotifyUrl": "https://open.spotify.com/search/Starstruck%20Jones%20RX"
    }
  ],
  "stats": {
    "trackCount": 19,
    "releaseCount": 8,
    "firstYear": "2023",
    "latestYear": "2026",
    "streams": "12,641",
    "monthlyListeners": "69",
    "topTrack": "Painful · 5,473"
  }
};
