/* GENERATED by tools/fetch_merch.py — do not edit by hand. */
window.MERCH = {
  "generated": true,
  "store": "https://sweltersounds.com/collections/jones",
  "items": [
    {
      "title": "Drop Dead Jacket",
      "url": "https://sweltersounds.com/collections/jones/products/jones-drop-dead-jacket",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/files/all-over-print-recycled-unisex-zip-hoodie-white-front-671c6e5a942f2_400x.jpg?v=1729916524",
      "price": "60",
      "priceMax": "73",
      "available": true,
      "variants": 11,
      "desc": "Drop Dead album art zip-up hoodie/jacket. • 95% recycled polyester, 5% spandex • Fabric weight 9.08 oz./yd.² (308 g/m²) • Soft, cotton-feel fabric outside and b"
    },
    {
      "title": "Drop Dead T-Shirt",
      "url": "https://sweltersounds.com/collections/jones/products/jones-drop-dead-t-shirt",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/files/unisex-staple-t-shirt-black-front-671c6fe71e0b3_400x.jpg?v=1729916922",
      "price": "16",
      "priceMax": "26.50",
      "available": true,
      "variants": 18,
      "desc": "Drop Dead album art T-Shirt • 100% combed and ring-spun cotton (Heather colors contain polyester) • Fabric weight: 4.2 oz./yd.² (142 g/m²) • Pre-shrunk fabric •"
    },
    {
      "title": "Eyez (New Low) Button Pin Set",
      "url": "https://sweltersounds.com/collections/jones/products/jones-eyez-new-low-button-pin-set",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/files/set-of-pin-buttons-white-2.25-front-65fe658e542da_400x.jpg?v=1711170968",
      "price": "10.50",
      "priceMax": "12",
      "available": true,
      "variants": 2,
      "desc": "\"Eyez\" button pin (set of 5) based on the album art from the song New Low by Jones. They’re lightweight, sturdy, and easy to put on. With a scratch and UV-resis"
    },
    {
      "title": "Eyez (New Low) Flag",
      "url": "https://sweltersounds.com/collections/jones/products/jones-eyez-new-low-flag",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/files/all-over-print-flag-white-front-65fe66c4bcf1a_400x.jpg?v=1711171285",
      "price": "27.95",
      "priceMax": "",
      "available": true,
      "variants": 1,
      "desc": "\"Eyez\" flag based on the album art from the song New Low by Jones. • 100% polyester • Knitted fabric • Fabric weight: 4.42 oz/yd² (150 g/m²) • Print on one side"
    },
    {
      "title": "Eyez (New Low) Framed Poster",
      "url": "https://sweltersounds.com/collections/jones/products/jones-eyez-new-low-framed-poster",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/files/enhanced-matte-paper-framed-poster-_in_-black-10x10-transparent-65fe6792dbb89_400x.jpg?v=1711171481",
      "price": "29.50",
      "priceMax": "53",
      "available": true,
      "variants": 15,
      "desc": "\"Eyez\" framed poster based on the album art from the song New Low by Jones. • Ayous wood .75″ (1.9 cm) thick frame from renewable forests • Paper thickness: 10."
    },
    {
      "title": "Eyez (New Low) Hat",
      "url": "https://sweltersounds.com/collections/jones/products/jones-eyez-new-low-hat",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/files/classic-dad-hat-black-front-65fe6157d435d_400x.jpg?v=1711169889",
      "price": "21",
      "priceMax": "",
      "available": true,
      "variants": 2,
      "desc": "\"Eyez\" hat based on the album art from the song New Low by Jones. • 100% chino cotton twill • Green Camo color is 35% chino cotton twill, 65% polyester • Unstru"
    },
    {
      "title": "Eyez (New Low) Zip Up Hoodie",
      "url": "https://sweltersounds.com/collections/jones/products/jones-eyez-new-low-zip-up-hoodie",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/files/all-over-print-recycled-unisex-zip-hoodie-white-left-front-65fe5f76a622d_400x.jpg?v=1711169417",
      "price": "62.99",
      "priceMax": "",
      "available": true,
      "variants": 11,
      "desc": "\"Eyez\" zip up hoodie based on the album art from the song New Low by Jones. Crafted from 95% recycled polyester, it combines sustainability with style. Soft bot"
    },
    {
      "title": "Fake Love Flag",
      "url": "https://sweltersounds.com/collections/jones/products/jones-fake-love-flag",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/all-over-print-flag-white-front-642b1948ae6a2_400x.jpg?v=1680546129",
      "price": "26.50",
      "priceMax": "",
      "available": true,
      "variants": 1,
      "desc": "Let them know you're done with Fake Love...or vice versa...but just make sure you're repping what you feel with this flag! Brighten up your space by adding this"
    },
    {
      "title": "Fake Love Hat",
      "url": "https://sweltersounds.com/collections/jones/products/jones-fake-love-hat",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/classic-dad-hat-black-front-642b178877876_400x.jpg?v=1680545686",
      "price": "24.50",
      "priceMax": "",
      "available": true,
      "variants": 5,
      "desc": "Fake Love hat. • 100% chino cotton twill • Green Camo color is 35% chino cotton twill, 65% polyester • Unstructured, 6-panel, low-profile • 6 embroidered eyelet"
    },
    {
      "title": "Fake Love Hoodie",
      "url": "https://sweltersounds.com/collections/jones/products/jones-fake-love-hoodie",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/unisex-premium-hoodie-black-front-642f5a960741a_400x.jpg?v=1680824999",
      "price": "47.50",
      "priceMax": "52.50",
      "available": true,
      "variants": 42,
      "desc": "Fake love is out there, but this will keep you warm. You won't regret buying this classic streetwear piece of apparel with a convenient pouch pocket and warm ho"
    },
    {
      "title": "Fake Love Sticker",
      "url": "https://sweltersounds.com/collections/jones/products/jones-fake-love-sticker",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/kiss-cut-stickers-white-3x3-default-642b197020b39_400x.jpg?v=1680546168",
      "price": "3",
      "priceMax": "3.50",
      "available": true,
      "variants": 3,
      "desc": "These stickers are printed on durable, high opacity adhesive vinyl which makes them perfect for regular use, as well as for covering other stickers or paint. Th"
    },
    {
      "title": "Fake Love Sweatpants",
      "url": "https://sweltersounds.com/collections/jones/products/jones-fake-love-sweatpants",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/unisex-fleece-sweatpants-black-front-left-642b19d93c3e7_400x.jpg?v=1680546288",
      "price": "61.39",
      "priceMax": "63.39",
      "available": true,
      "variants": 42,
      "desc": "Well-made and lined with fleece, these comfortable Unisex Fleece Sweatpants will be your first choice for a casual everyday outfit—all you need to add is a grap"
    },
    {
      "title": "Fake Love Sweatshirt",
      "url": "https://sweltersounds.com/collections/jones/products/jones-fake-love-sweatshirt",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/unisex-organic-sweatshirt-black-front-642f5b45642ad_400x.jpg?v=1680825170",
      "price": "47.50",
      "priceMax": "",
      "available": true,
      "variants": 25,
      "desc": "When you need to warm up from all the Fake Love out there, but don't quite need a hoodie. We got you! The Unisex organic sweatshirt is made of organic and recyc"
    },
    {
      "title": "Fake Love T-Shirt (Unisex)",
      "url": "https://sweltersounds.com/collections/jones/products/jones-fake-love-t-shirt-unisex",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/unisex-staple-t-shirt-black-front-642f5942c79f9_400x.jpg?v=1680824669",
      "price": "17",
      "priceMax": "27",
      "available": true,
      "variants": 100,
      "desc": "Fake love never looked so good. This t-shirt feels soft and lightweight, with the right amount of stretch. It's comfortable and flattering for all. • 100% combe"
    },
    {
      "title": "Fake Love Tie Dye Hoodie",
      "url": "https://sweltersounds.com/collections/jones/products/jones-fake-love-tie-dye-hoodie",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/unisex-champion-tie-dye-hoodie-mulled-berry-front-642b181ede60b_400x.jpg?v=1680545838",
      "price": "81.50",
      "priceMax": "84",
      "available": true,
      "variants": 15,
      "desc": "Fake Love never looked so good. If you're looking for a trendy, one-of-a-kind clothing item, this Champion tie-dye hoodie is the one! It's almost impossible to "
    },
    {
      "title": "Lost CTRL Album Art Canvas",
      "url": "https://sweltersounds.com/collections/jones/products/jones-lost-ctrl-album-art-canvas",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/files/canvas-_in_-14x14-wall-665bf13ee0fbd_400x.jpg?v=1717301578",
      "price": "26.50",
      "priceMax": "",
      "available": true,
      "variants": 1,
      "desc": "Jones - Lost CTRL Album Art Canvas • 1.25″ (3.18 cm) thick poly-cotton blend canvas • Canvas fabric weight: 10.15 +/- 0.74 oz./yd.² (344 g/m² +/- 25g/m²) • Fade"
    },
    {
      "title": "Lost CTRL Hat",
      "url": "https://sweltersounds.com/collections/jones/products/jones-lost-ctrl-hat-2",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/files/classic-dad-hat-black-front-665bf50541cba_400x.jpg?v=1717302540",
      "price": "27",
      "priceMax": "",
      "available": true,
      "variants": 1,
      "desc": "Jones - Lost CTRL Hat • 100% chino cotton twill • Green Camo color is 35% chino cotton twill, 65% polyester • Unstructured, 6-panel, low-profile • 6 embroidered"
    },
    {
      "title": "Lost CTRL Hoodie",
      "url": "https://sweltersounds.com/collections/jones/products/jones-lost-ctrl-hoodie",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/files/all-over-print-recycled-unisex-hoodie-white-front-665bede5adcce_400x.jpg?v=1717300726",
      "price": "55",
      "priceMax": "57.50",
      "available": true,
      "variants": 11,
      "desc": "Jones - Lost CTRL Hoodie. This comfy unisex hoodie has a soft outside with a vibrant print and an even softer brushed fleece inside. • 95% recycled polyester, 5"
    },
    {
      "title": "Lost CTRL Media Art Framed Poster",
      "url": "https://sweltersounds.com/collections/jones/products/jones-lost-ctrl-media-art-framed-poster",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/files/enhanced-matte-paper-framed-poster-_in_-black-12x18-transparent-665bf25151c1a_400x.jpg?v=1717301849",
      "price": "44",
      "priceMax": "",
      "available": true,
      "variants": 1,
      "desc": "Jones - Lost CTRL Media Art Framed Poster • Ayous wood .75″ (1.9 cm) thick frame from renewable forests • Paper thickness: 10.3 mil (0.26 mm) • Paper weight: 18"
    },
    {
      "title": "Lost CTRL T-Shirt",
      "url": "https://sweltersounds.com/collections/jones/products/jones-lost-ctrl-t-shirt",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/files/all-over-print-mens-crew-neck-t-shirt-white-front-665bf586e247d_400x.jpg?v=1717302674",
      "price": "31",
      "priceMax": "32.50",
      "available": true,
      "variants": 6,
      "desc": "Jones - Lost CTRL T-Shirt • 95% polyester, 5% elastane (fabric composition may vary by 1%) • Premium knit mid-weight jersey • Four-way stretch fabric that stret"
    },
    {
      "title": "Lost CTRL Track Pants",
      "url": "https://sweltersounds.com/collections/jones/products/jones-lost-ctrl-track-pants",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/files/all-over-print-unisex-track-pants-white-front-665bef51aada7_400x.jpg?v=1717301090",
      "price": "37.50",
      "priceMax": "",
      "available": true,
      "variants": 7,
      "desc": "Jones - Lost CTRL Track Pants. The water-resistant, lightweight fabric and mesh lining provide comfort, while elastic ankle cuffs will make it easy for you to s"
    },
    {
      "title": "Vices Backpack",
      "url": "https://sweltersounds.com/collections/jones/products/jones-vices-backpack",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/all-over-print-backpack-white-front-642b18ca0ade2_400x.jpg?v=1680546003",
      "price": "42.50",
      "priceMax": "",
      "available": true,
      "variants": 1,
      "desc": "Need more than our fanny pack to store all your Vices? We got you. This medium size backpack is just what you need for daily use or sports activities! The pocke"
    },
    {
      "title": "Vices Fanny Pack",
      "url": "https://sweltersounds.com/collections/jones/products/jones-vices-fanny-pack",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/all-over-print-fanny-pack-white-front-left-642b17bfd7195_400x.jpg?v=1680545736",
      "price": "32.50",
      "priceMax": "",
      "available": true,
      "variants": 2,
      "desc": "Store all your Vices with this fanny pack. This fanny pack is the ultimate accessory for people on the go. And this waist bag has everything—the right size, a s"
    },
    {
      "title": "Vices Flag",
      "url": "https://sweltersounds.com/collections/jones/products/jones-vices-flag",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/all-over-print-flag-white-front-642b19022a8dd_400x.jpg?v=1680546060",
      "price": "26.50",
      "priceMax": "",
      "available": true,
      "variants": 1,
      "desc": "Hoist your Vices high with this Jones flag. Brighten up your space by adding this unique flag to your wall. Your flag won’t crease or shrink thanks to the polye"
    },
    {
      "title": "Vices Hat",
      "url": "https://sweltersounds.com/collections/jones/products/jones-vices-hat",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/classic-dad-hat-black-front-642b1a7c85093_400x.jpg?v=1680546454",
      "price": "24.50",
      "priceMax": "",
      "available": true,
      "variants": 1,
      "desc": "Put your Vices on display with this Jones Vices hat! • 100% chino cotton twill • Green Camo color is 35% chino cotton twill, 65% polyester • Unstructured, 6-pan"
    },
    {
      "title": "Vices Hoodie",
      "url": "https://sweltersounds.com/collections/jones/products/jones-vices-hoodie",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/unisex-premium-hoodie-black-front-642b1cad31fc7_400x.jpg?v=1680547003",
      "price": "47.50",
      "priceMax": "52.50",
      "available": true,
      "variants": 18,
      "desc": "Soft hoodie to make you feel more comfortable about those Vices. You won't regret buying this classic streetwear piece of apparel with a convenient pouch pocket"
    },
    {
      "title": "Vices Oversized Tie Dye T-Shirt",
      "url": "https://sweltersounds.com/collections/jones/products/jones-vices-oversized-tie-dye-t-shirt",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/oversized-tie-dye-t-shirt-milky-way-front-642b18aa60254_400x.jpg?v=1680545972",
      "price": "29",
      "priceMax": "31.50",
      "available": true,
      "variants": 5,
      "desc": "Come to terms with your Vices and look good doing it. The tee has a cool, relaxed fit and is highly durable thanks to its heavyweight cotton material. Join the "
    },
    {
      "title": "Vices Sticker",
      "url": "https://sweltersounds.com/collections/jones/products/jones-vices-sticker",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/kiss-cut-stickers-white-3x3-default-642b198f7905b_400x.jpg?v=1680546205",
      "price": "3",
      "priceMax": "3.50",
      "available": true,
      "variants": 3,
      "desc": "These stickers are printed on durable, high opacity adhesive vinyl which makes them perfect for regular use, as well as for covering other stickers or paint. Th"
    },
    {
      "title": "Vices Sweatpants",
      "url": "https://sweltersounds.com/collections/jones/products/jones-vices-sweatpants",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/unisex-fleece-sweatpants-black-front-left-642b1a0b99375_400x.jpg?v=1680546385",
      "price": "61.39",
      "priceMax": "63.39",
      "available": true,
      "variants": 18,
      "desc": "Well-made and lined with fleece, these comfortable Unisex Fleece Sweatpants will be your first choice for a casual everyday outfit—all you need to add is a grap"
    },
    {
      "title": "Vices Sweatshirt",
      "url": "https://sweltersounds.com/collections/jones/products/jones-vices-sweatshirt",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/unisex-organic-sweatshirt-black-front-642b1d17d6e0b_400x.jpg?v=1680547118",
      "price": "47.50",
      "priceMax": "",
      "available": true,
      "variants": 15,
      "desc": "Vices keep ya warm! The Unisex organic sweatshirt is made of organic and recycled materials, and feels soft and cozy to the touch. It has set-in sleeves, 2×2 ri"
    },
    {
      "title": "Vices T-Shirt (Unisex)",
      "url": "https://sweltersounds.com/collections/jones/products/jones-vices-t-shirt-unisex",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/unisex-staple-t-shirt-black-front-642f58c69c60e_400x.jpg?v=1680824532",
      "price": "17",
      "priceMax": "27",
      "available": true,
      "variants": 43,
      "desc": "Display your vices. This t-shirt feels soft and lightweight, with the right amount of stretch. It's comfortable and flattering for all. • 100% combed and ring-s"
    },
    {
      "title": "Fake Love Crop Top",
      "url": "https://sweltersounds.com/collections/jones/products/jones-fake-love-crop-top",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/womens-crop-tee-black-front-642b17493d97b_400x.jpg?v=1680545618",
      "price": "22",
      "priceMax": "",
      "available": false,
      "variants": 2,
      "desc": "Fed up with Fake Love? This crop top is one that you can actually love instead. The season's trendiest garment - the crop top. This top is tight-fitting but sti"
    },
    {
      "title": "Vices Tie Dye Hoodie",
      "url": "https://sweltersounds.com/collections/jones/products/jones-vices-tie-dye-hoodie",
      "img": "https://cdn.shopify.com/s/files/1/0714/5393/3876/products/unisex-champion-tie-dye-hoodie-black-front-642b1861d2ad3_400x.jpg?v=1680545905",
      "price": "81.50",
      "priceMax": "84",
      "available": false,
      "variants": 5,
      "desc": "It's not a Vice if it looks nice right? If you're looking for a trendy, one-of-a-kind clothing item, this Champion tie-dye hoodie is the one! It's almost imposs"
    }
  ]
};
