#!/usr/bin/env python3
"""Bake the Swelter Sounds merch collection into js/merch-data.js.

The storefront sends X-Frame-Options: DENY, so the shop cannot be embedded in
an iframe. Instead we mirror the public products.json into a small payload and
render it natively.

Variant ids are mirrored too, so the OS can build its own cart and hand the
whole thing to Shopify as a cart permalink:
    https://sweltersounds.com/cart/<variant>:<qty>,<variant>:<qty>
which drops the buyer into a real checkout with everything already in it. No
API key is involved; cart permalinks are a documented public Shopify feature.
"""
import html
import json
import pathlib
import re
import sys
import urllib.request

SHOP = "https://sweltersounds.com"
COLLECTION = SHOP + "/collections/jones"
SRC = COLLECTION + "/products.json?limit=250"
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "js" / "merch-data.js"

# Shopify's product_type is blank on every item in this collection and the only
# tag is "jones", so the category has to be derived from the title.
KINDS = [
    ("Hoodie",    r"hoodie|zip[- ]?up|sweatshirt|crewneck|jacket"),
    ("Tee",       r"t-?shirt|tee\b|crop top"),
    ("Pants",     r"sweatpants|track pants|joggers|leggings|shorts"),
    ("Hat",       r"\bhat\b|\bcap\b|beanie|visor"),
    ("Bag",       r"tote|backpack|fanny pack|pouch|\bbag\b"),
    ("Wall Art",  r"poster|canvas|flag|tapestry"),
    ("Sticker",   r"sticker|pin set|\bpins?\b|magnet"),
    ("Drinkware", r"mug|tumbler|bottle"),
    ("Home",      r"pillow|blanket|towel|curtain|mouse ?pad|desk ?mat|rug"),
    ("Case",      r"case|skin\b"),
]


def kind_of(title):
    for name, pat in KINDS:
        if re.search(pat, title, re.I):
            return name
    return "Other"


def plain(body):
    """First readable sentence of the Shopify body_html."""
    txt = re.sub(r"<[^>]+>", " ", body or "")
    txt = html.unescape(txt).replace("\u00a0", " ")
    txt = re.sub(r"\s+", " ", txt).strip()
    return txt[:160]


def thumb(src, px=400):
    """Shopify serves resized variants by filename suffix."""
    return re.sub(r"(\.(?:jpg|jpeg|png|webp))(\?|$)", rf"_{px}x\1\2", src, flags=re.I)


def money(v):
    """$60 stays bare, $10.50 keeps its cents."""
    return f"{v:.0f}" if float(v).is_integer() else f"{v:.2f}"


def previous():
    if not OUT.exists():
        return None
    m = re.search(r"window\.MERCH\s*=\s*(\{.*\});", OUT.read_text(), re.S)
    return json.loads(m.group(1)) if m else None


def main():
    req = urllib.request.Request(SRC, headers={"User-Agent": "jonesrx-site-build/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            raw = json.loads(r.read().decode("utf-8"))
    except Exception as e:
        prev = previous()
        print(f"  merch: fetch failed ({e})")
        if prev:
            print(f"  merch: keeping {len(prev.get('items', []))} previously published items")
            return 0
        print("  merch: no previous data to fall back on", file=sys.stderr)
        return 1

    items = []
    for p in raw.get("products", []):
        variants = p.get("variants") or []
        prices = [float(v["price"]) for v in variants if v.get("price")]
        if not prices:
            continue
        title = p["title"].replace("Jones - ", "").strip()
        opts = [o["name"] for o in p.get("options", [])]
        # a lone "Title" option means there is no real choice to make
        single = opts == ["Title"]
        items.append({
            "title": title,
            "url": f"{COLLECTION}/products/{p['handle']}",
            "img": thumb(p["images"][0]["src"]) if p.get("images") else "",
            "price": money(min(prices)),
            "priceMax": money(max(prices)) if max(prices) != min(prices) else "",
            "low": round(min(prices), 2),
            "available": any(v.get("available") for v in variants),
            "kind": kind_of(title),
            "added": (p.get("published_at") or p.get("created_at") or "")[:10],
            "opts": [] if single else opts,
            # [variant id, variant title, price, in stock]
            "vars": [[str(v["id"]), v["title"], money(float(v["price"])),
                      1 if v.get("available") else 0] for v in variants],
            "desc": plain(p.get("body_html")),
        })

    items.sort(key=lambda i: (not i["available"], i["title"]))
    payload = {"generated": True, "store": COLLECTION, "shop": SHOP, "items": items}
    OUT.write_text(
        "/* GENERATED by tools/fetch_merch.py \u2014 do not edit by hand. */\n"
        f"window.MERCH = {json.dumps(payload, separators=(',', ':'), ensure_ascii=False)};\n")
    live = sum(1 for i in items if i["available"])
    nvar = sum(len(i["vars"]) for i in items)
    kb = OUT.stat().st_size / 1024
    print(f"  merch: {len(items)} products ({live} in stock), {nvar} variants "
          f"-> {OUT.relative_to(ROOT)} ({kb:.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
