#!/usr/bin/env python3
"""Bake the Swelter Sounds merch collection into js/merch-data.js.

The storefront sends X-Frame-Options: DENY, so the shop cannot be embedded in
an iframe. Instead we mirror the public products.json into a small payload and
render it natively; the buy buttons deep-link back to the real product pages.
"""
import html
import json
import pathlib
import re
import sys
import urllib.request

COLLECTION = "https://sweltersounds.com/collections/jones"
SRC = COLLECTION + "/products.json?limit=250"
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "js" / "merch-data.js"


def plain(body):
    """First readable sentence of the Shopify body_html."""
    txt = re.sub(r"<[^>]+>", " ", body or "")
    txt = html.unescape(txt).replace("\u00a0", " ")
    txt = re.sub(r"\s+", " ", txt).strip()
    return txt[:160]


def thumb(src, px=400):
    """Shopify serves resized variants by filename suffix."""
    return re.sub(r"(\.(?:jpg|jpeg|png|webp))(\?|$)", rf"_{px}x\1\2", src, flags=re.I)


def money(v):
    """$60 stays bare, $10.50 keeps its cents."""
    return f"{v:.0f}" if float(v).is_integer() else f"{v:.2f}"


def previous():
    if not OUT.exists():
        return None
    m = re.search(r"window\.MERCH\s*=\s*(\{.*\});", OUT.read_text(), re.S)
    return json.loads(m.group(1)) if m else None


def main():
    req = urllib.request.Request(SRC, headers={"User-Agent": "jonesrx-site-build/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            raw = json.loads(r.read().decode("utf-8"))
    except Exception as e:
        prev = previous()
        print(f"  merch: fetch failed ({e})")
        if prev:
            print(f"  merch: keeping {len(prev.get('items', []))} previously published items")
            return 0
        print("  merch: no previous data to fall back on", file=sys.stderr)
        return 1

    items = []
    for p in raw.get("products", []):
        variants = p.get("variants") or []
        prices = [float(v["price"]) for v in variants if v.get("price")]
        if not prices:
            continue
        items.append({
            "title": p["title"].replace("Jones - ", "").strip(),
            "url": f"{COLLECTION}/products/{p['handle']}",
            "img": thumb(p["images"][0]["src"]) if p.get("images") else "",
            "price": money(min(prices)),
            "priceMax": money(max(prices)) if max(prices) != min(prices) else "",
            "available": any(v.get("available") for v in variants),
            "variants": len(variants),
            "desc": plain(p.get("body_html")),
        })

    items.sort(key=lambda i: (not i["available"], i["title"]))
    payload = {"generated": True, "store": COLLECTION, "items": items}
    OUT.write_text(
        "/* GENERATED by tools/fetch_merch.py \u2014 do not edit by hand. */\n"
        f"window.MERCH = {json.dumps(payload, indent=2, ensure_ascii=False)};\n")
    live = sum(1 for i in items if i["available"])
    print(f"  merch: {len(items)} products ({live} in stock) -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
